# ShadowItemEdit Configuration File
# ---------------------------------
database:
  type: sqlite # sqlite or mysql
  host: localhost
  port: 3306
  database: shadowitemedit
  username: root
  password: ""

settings:
  undo-limit: 10 # Number of undo actions stored per player session
  save-clipboard-on-quit: true
